apiVersion: v1
kind: Service
metadata:
  name: nodejs
  namespace: namespace-workflow-1729311143510
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000